name: proyecto_visitas
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  postgres: ^2.5.2

dev_dependencies:
  flutter_lints: ^2.0.0
flutter_test:
  sdk: flutter

flutter:
  uses-material-design: true
