name: proyecto_visitas
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.17.0
  postgres: ^2.5.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.3.56

dev_dependencies:
  flutter_lints: ^2.0.0
flutter_test:
  sdk: flutter

flutter:
  assets:
  - assets/logo.png
  - assets/mined.jpg
  uses-material-design: true